# Generated by Django 6.0 on 2025-12-23 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('extracted_data', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['-uploaded_at'], name='api_documen_uploade_eff967_idx'), models.Index(fields=['status'], name='api_documen_status_4324ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtractedFundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(blank=True, max_length=500, null=True)),
                ('fund_code', models.CharField(blank=True, max_length=100, null=True)),
                ('management_fee', models.CharField(blank=True, max_length=200, null=True)),
                ('custodian_bank', models.CharField(blank=True, max_length=300, null=True)),
                ('portfolio', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_data', to='api.document')),
            ],
            options={
                'verbose_name': 'Extracted Fund Data',
                'verbose_name_plural': 'Extracted Fund Data',
            },
        ),
    ]
