# Generated by Django 6.0 on 2025-12-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedfunddata',
            name='dividend_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='management_company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='nav_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='redemption_fee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='subscription_fee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='switching_fee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
