# Generated by Django 6.0 on 2025-12-29 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_extractedfunddata_dividend_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='optimized_file',
            field=models.FileField(blank=True, null=True, upload_to='optimized_documents/%Y/%m/%d/'),
        ),
    ]
