# Generated by Django 6.0 on 2025-12-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_optimized_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ocr_model',
            field=models.CharField(choices=[('gemini', 'Gemini 2.0 Flash'), ('mistral', 'Mistral Large')], default='gemini', max_length=20),
        ),
    ]
