# Generated by Django 6.0 on 2025-12-31 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_document_ocr_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page_metadata',
            field=models.JSONField(blank=True, help_text='Metadata about selected pages and matched keywords', null=True),
        ),
    ]
