# Generated by Django 6.0 on 2026-01-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_extractedfunddata_management_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ocr_model',
            field=models.CharField(choices=[('gemini', 'Gemini 2.0 Flash'), ('mistral', 'Mistral Large'), ('mistral-ocr', 'Mistral OCR + Small')], default='gemini', max_length=20),
        ),
    ]
