# Generated by Django 6.0 on 2026-01-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_document_chat_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedfunddata',
            name='analysis_report',
            field=models.JSONField(blank=True, help_text='AI-generated investment evaluation', null=True),
        ),
    ]
