# Generated by Django 6.0 on 2026-01-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_extractedfunddata_analysis_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedfunddata',
            name='asset_allocation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='auditor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='benchmark',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='concentration_risk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='cut_off_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='interest_rate_risk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='investment_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='investment_strategy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='investment_style',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='liquidity_risk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='minimum_investment',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='sector_focus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='total_expense_ratio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='trading_frequency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
