# Generated by Django 6.0 on 2026-01-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_extractedfunddata_asset_allocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedfunddata',
            name='audit_fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='borrowing_limit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='custody_fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='distribution_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='fund_supervisor',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='fund_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='investment_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='investor_rights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='legal_structure',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='leverage_limit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='license_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='nav_calculation_frequency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='nav_publication',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='other_expenses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='pricing_source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='regulator',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='sales_channels',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='settlement_cycle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='supervisory_fee',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='extractedfunddata',
            name='valuation_method',
            field=models.TextField(blank=True, null=True),
        ),
    ]
