# Generated by Django 6.0 on 2026-02-17 10:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_documentchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='chunk_search_vector_idx'),
        ),
    ]
