# Generated by Django 6.0 on 2026-02-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_documentchunk_search_vector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='content_ascii',
            field=models.TextField(blank=True, null=True),
        ),
    ]
